### ISSUE TITLE
[bug]: make fails to build at mser object

### ISSUE THREAD

**Issue by kalwalt** [wlzhao22/lip-vireo#2]
With the latest code from master branch if you run the make command it will fail with this error message:
`make: ***  No rules to generate the objective «obj/Debug/mser.o», needed for «out_debug».  Stop.`
This is because mser.cpp file doen't exist, if you remove `$(OBJDIR_DEBUG)/mser.o` from the Makefile it will compile.
This is correct?

**Comment by wlzhao22** [comment]
I modified the Makefile. "obj/Debug/mser.o" is omitted.

**Comment by kalwalt** [comment]
> I modified the Makefile. "obj/Debug/mser.o" is omitted.

Perfect! thank you!
